replicaCount: 1
namespace: waii

image:
  repository: "waiilabs/sandbox"
  tag: "latest"
  digest: "sha256:46f1c56cc8daefd570067db9f06611f0e203aea9a60b88b554d8cec6bbcb5fb9"
  pullPolicy: Always
  platform: linux/amd64

service:
  type: ClusterIP
  port: 3456

env:
  enableLogStreamingDocker: true
  enableLogStreamingApplication: true
  # redirectLogsDocker is ignored if enableLogStreamingDocker is true
  redirectLogsDocker: false
  loadSampleDb: true
  simplePassword: true
  
  rds:
    override: false # If false, all values ignored
    host: localhost
    port: 5432
    user: postgres
    password:
      secret: rds-secret # First preference
      hardcoded: mypassword # Fallback
    database: database

resources:
  requests:
    cpu: "1000m"    
    memory: "1Gi"  
  limits:
    cpu: "4000m" 
    memory: "16Gi" 

imagePullSecrets:
  - name: regcred