replicaCount: 1
image:
  repository: "waiilabs/sandbox"
  tag: latest
  pullPolicy: IfNotPresent
  platform: linux/amd64
service:
  type: ClusterIP
  port: 3456
env:
  openaiApiKey: ''
  endpointConfigFile: '/root/waii-llm-config/llm_endpoints.yml'
  waiiDefaultApiKey: ''
imagePullSecrets:
  - name: regcred
