apiVersion: v1
kind: ConfigMap
metadata:
  name: waii-conf
data:
  azure-openai.conf: |
    - name: gpt-3.5-turbo
      endpoints:
        - api_type: azure
          api_key: <YOUR_AZURE_API_KEY>
          api_base: https://<YOUR_AZURE_ENDPOINT>.openai.azure.com/
          deployment_name: gpt-35
    - name: gpt-4
      endpoints:
        - api_key: <YOUR_AZURE_API_KEY>
          api_base: https://<YOUR_AZURE_ENDPOINT>.openai.azure.com/
          deployment_name: gpt-4
    - name: gpt-4-1106-preview
      endpoints:
        - api_key: <YOUR_AZURE_API_KEY>
          api_base: https://<YOUR_AZURE_ENDPOINT>.openai.azure.com/
          deployment_name: gpt-4-1106
    - name: text-embedding-ada-002
      endpoints:
        - api_key: <YOUR_AZURE_API_KEY>
          api_base: https://<YOUR_AZURE_ENDPOINT>.openai.azure.com/
          deployment_name: ada2
