apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "waii.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "waii.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "waii.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SKIP_PRELOAD_DATA
          value: "true"
        - name: REDIRECT_LOG
          value: "1"
        - name: RDS_URL
          valueFrom:
            secretKeyRef:
              name: waii-rds-creds
              key: rdsUrl
        - name: SIMPLE_PASSWORD
          value: "true"
        - name: OPENAI_API_KEY
          value: "{{ .Values.env.openaiApiKey }}"
        - name: WAII_DEFAULT_API_KEY
          value: "{{ .Values.env.waiiDefaultApiKey }}"
        ports:
        - containerPort: 3456
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              if [ -n "$WAII_DEFAULT_API_KEY" ]; then
                curl -X POST -H "Content-Type: application/json" -H "authorization: Bearer $WAII_DEFAULT_API_KEY" http://localhost:3456/api/health-check --data-raw '{"scope":"","org_id":"","user_id":""}'
              else
                curl -X POST -H "Content-Type: application/json" http://localhost:3456/api/health-check --data-raw '{"scope":"","org_id":"","user_id":""}'
              fi
          initialDelaySeconds: 180
          periodSeconds: 60
          failureThreshold: 6 
          timeoutSeconds: 5 
        volumeMounts:
        - name: logs
          mountPath: /tmp/logs
        - name: waii-storage
          mountPath: /root/.waii_storage
        - name: waii-models-config
          mountPath: /waii/models.config
          subPath: models.config
        - name: waii-llm-config
          mountPath: /waii/llm_endpoint.config
          subPath: llm_endpoint.config 
      dnsConfig:
        options:
          - name: edns0
      volumes:
      - name: logs
        emptyDir: {}
      - name: waii-storage
        emptyDir: {}
      - name: waii-models-config
        configMap:
          name: waii-models-config
      - name: waii-llm-config
        secret:
          secretName: waii-llm-config