apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "waii.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "waii.labels" . | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_22=We need write access for Nginx logs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "waii.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "waii.name" . }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true 
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001  
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: 
        - "--api_key_auth_enabled"
        securityContext:
          privileged: false           
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST -H "Content-Type: application/json" http://localhost:3456/api/ping --data-raw '{"scope":"","org_id":"","user_id":""}'
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST -H "Content-Type: application/json" http://localhost:3456/api/ping --data-raw '{"scope":"","org_id":"","user_id":""}'
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 6 
          timeoutSeconds: 5 
        env:
        - name: SKIP_PRELOAD_DATA
          value: "true"
        - name: SIMPLE_PASSWORD
          value: "{{ .Values.env.simplePassword }}"
        - name: LOAD_SAMPLE_DB
          value: "{{ .Values.env.loadSampleDb }}"
        - name: NGINX_TEMP_PATH
          value: "/tmp/nginx"
        {{- if (default true .Values.env.enableLogStreamingDocker) }}
        - name: ENABLE_LOG_STREAMING_DOCKER
          value: "true"
        {{- end }}
        {{- if (default true .Values.env.enableLogStreamingApplication) }}
        - name: ENABLE_LOG_STREAMING_APPLICATION
          value: "true"
        {{- end }}
        {{- if (default false .Values.env.redirectLogsDocker) }}
        - name: REDIRECT_LOGS_DOCKER
          value: "true"
        {{- end }}
        {{- if (default false .Values.env.rds.override) }}
        - name: PGHOST
          value: {{ .Values.env.rds.host | quote }}
        - name: PGUSER
          value: {{ .Values.env.rds.user | quote }}
        {{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.env.rds.password.secret }}
        {{- if $secret }}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.rds.password.secret }}
              key: password
        {{- else }}
        - name: PGPASSWORD
          value: {{ .Values.env.rds.password.hardcoded }}
        {{- end }}
        - name: PGPORT
          value: {{ .Values.env.rds.port | quote }}
        - name: PGDATABASE
          value: {{ .Values.env.rds.database | quote }}
        {{- end }}
        ports:
        - containerPort: 3456
        volumeMounts:
        - name: logs
          mountPath: /tmp/logs
        - name: waii-storage
          mountPath: /.waii_storage
        - name: waii-models-config
          mountPath: /waii/models.config
          subPath: models.config
        - name: waii-llm-config
          mountPath: /waii/llm_endpoint.config
          subPath: llm_endpoint.config
        {{- if not (default false .Values.rds.useEnvVars) }}
        - name: rds-url
          mountPath: /mnt/secrets/rds/rdsurl
          subPath: RDS_URL
        {{- end }}
        - name: openai-secret
          mountPath: /mnt/secrets/openai/api-key
          subPath: openaiApiKey
          readOnly: true
        - name: waii-secret
          mountPath: /mnt/secrets/waii/api-key
          subPath: waiiDefaultApiKey
          readOnly: true
        - name: nginx-temp
          mountPath: /tmp/nginx
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run/nginx
        - name: nginx-logs
          mountPath: /var/log/nginx
      volumes:
      - name: logs
        emptyDir: {}
      - name: waii-storage
        emptyDir: {}
      - name: waii-models-config
        configMap:
          name: waii-models-config
          optional: true
      - name: waii-llm-config
        secret:
          secretName: waii-llm-config
          optional: true
      - name: openai-secret
        secret:
          secretName: waii-secrets
          optional: true
      - name: waii-secret
        secret:
          secretName: waii-secrets
          optional: true
      {{- if not (default false .Values.env.rds.override) }}
      - name: rds-url
        secret:
          secretName: waii-rds-creds
      {{- end }}
      - name: nginx-temp
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}