# Comment out this secret if you want to use hardcoded password from {{ .Values.env.rds.password.hardcoded }}
{{- if (default false .Values.env.rds.override) }}
apiVersion: v1
kind: Secret
metadata:
  name: rds-secret  # This must match `{{ .Values.env.rds.password.secret }}`
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: cGFzc3dvcmQ=  # Base64-encoded value of the password, can fallback from `{{ .Values.env.rds.password.hardcoded }}`
{{- end }}