apiVersion: v1
kind: Service
metadata:
  name: waii-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "waii.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3456
      protocol: TCP
      name: http
  selector:
    {{- include "waii.selectorLabels" . | nindent 6 }}