apiVersion: v1
kind: Service
metadata:
  name: waii-svc
  labels:
    {{- include "waii.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3456
      targetPort: 3456
      protocol: TCP
      name: http
  selector:
    {{- include "waii.selectorLabels" . | nindent 6 }}
