{{- $ns := .Values.namespace | default .Release.Namespace }}
{{- if not ( lookup "v1" "Secret" $ns .Values.dockerRegistry.secret ) }}
{{- $registry := .Values.dockerRegistry.url }}
{{- $username := .Values.dockerRegistry.username }}
{{- $password := .Values.dockerRegistry.password }}
{{- $auth := ( printf "%s:%s" $username $password ) | b64enc }}
{{- $dockerConfigJson := ( dict "auths" ( dict $registry ( dict "username" $username "password" $password "auth" $auth ) ) ) | toJson | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistry.secret }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfigJson }}
{{- end }}
