{{- $ns := .Values.namespace | default .Release.Namespace }}
{{- if and ( not .Values.secrets.waiiSecrets.data.openaiApiKey ) ( not ( lookup "v1" "Secret" $ns .Values.secrets.llmEndpointConfig.secret ) ) }}
{{- $raw := .Values.files.llmEndpointConfig.rawContent | default ( .Files.Get "files/llm_endpoint_config.yaml" ) }}
{{- $rendered := tpl $raw . }}
{{- $encoded := $rendered | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.llmEndpointConfig.secret }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  llm_endpoint.config: {{ $encoded }}
{{- end }}
