{{- $ns := .Values.namespace | default .Release.Namespace }}
{{- if and ( .Values.env.rds.override | default false ) ( not ( lookup "v1" "Secret" $ns .Values.env.rds.password.secret ) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.rds.password.secret }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  password: {{ .Values.env.rds.password.hardcoded | b64enc }}
{{- end }}
