{{- $ns := .Values.namespace | default .Release.Namespace }}
{{- if and .Values.secrets.rdsUrl.data.rdsUrl ( not ( lookup "v1" "Secret" $ns .Values.secrets.rdsUrl.secret ) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rdsUrl.secret }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  RDS_URL: {{ .Values.secrets.rdsUrl.data.rdsUrl | b64enc }}
{{- end }}
