apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default ( include "waii.fullname" . ) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "waii.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "waii.selectorLabels" . | nindent 4 }}
