{{- $ns := .Values.namespace | default .Release.Namespace }}
{{- if and ( or .Values.secrets.waiiSecrets.data.openaiApiKey .Values.secrets.waiiSecrets.data.waiiDefaultApiKey ) ( not ( lookup "v1" "Secret" $ns .Values.secrets.waiiSecrets.secret ) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.waiiSecrets.secret }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  openaiApiKey: {{ .Values.secrets.waiiSecrets.data.openaiApiKey | b64enc }}
  waiiDefaultApiKey: {{ .Values.secrets.waiiSecrets.data.waiiDefaultApiKey | b64enc }}
{{- end }}
